name: Aiven MySQL Wake Up

on:
workflow_dispatch:

jobs:
wake-aiven:
runs-on: ubuntu-latest

```
steps:
  - name: Install Aiven CLI
    run: pip install aiven-client

  - name: Check Aiven service
    run: avn --auth-token "${{ secrets.AIVEN_API_TOKEN }}" --project "${{ secrets.AIVEN_PROJECT }}" service get "${{ secrets.AIVEN_SERVICE }}"

  - name: Power on MySQL
    run: avn --auth-token "${{ secrets.AIVEN_API_TOKEN }}" --project "${{ secrets.AIVEN_PROJECT }}" service update "${{ secrets.AIVEN_SERVICE }}" --power-on

  - name: Wait for MySQL
    run: avn --auth-token "${{ secrets.AIVEN_API_TOKEN }}" --project "${{ secrets.AIVEN_PROJECT }}" service wait "${{ secrets.AIVEN_SERVICE }}"

  - name: Finished
    run: echo "Aiven MySQL is running."
```
